### PR TITLE
NESJI-1: create initial dashboard component

### PR DESCRIPTION
**Pull request by noydb**
Figma: https://www.figma.com/file/eES3yqs6YyEtZR9aQclM0w/Jira-Dashboard?node-id=1%3A149&mode=dev

Screenshot 2024-04-04 at 12 26 06

Screenshot 2024-04-04 at 12 26 35

### CODE REVIEW

**Review by colsen-neslo — APPROVED** [review]

**Comment by colsen-neslo** [comment]
Do you have a screenshot of what the dashboard currently looks like?

**Comment by noydb** [comment]
Figma: https://www.figma.com/file/eES3yqs6YyEtZR9aQclM0w/Jira-Dashboard?node-id=1%3A149&mode=dev

Screenshot 2024-04-04 at 12 26 06

Screenshot 2024-04-04 at 12 26 35

**Comment by colsen-neslo** [comment]
Is the estimated column the committed story points for the sprint? And is there a plan to show how many story points are in review for example?

**Comment by noydb** [comment]
For now we're keeping everything not in completed, as in progress, just so we have a very summarized view of what needs to be done. we can easily break these columns up however into column per status

**Review by JOlsen-Neslo — APPROVED** [review]

**Pull request merged**
